### ISSUE TITLE
Use Phi-Accrual Detection for failure detection 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/scuttlebutt#12]
https://www.researchgate.net/publication/29682135_The_ph_accrual_failure_detector

**Comment by evanxg852000** [comment]
With my attempted implementation, I am currently proposing the failure detector to be member of ScuttleButt.

```rust
ScuttleButt {
...
failure_detector: FailureDetector,
}

impl ScuttleBut {
  fn live_nodes(); // access list of live nodes
  fn dead_nodes(); // access list of dead nodes
}
```
`FailureDetector` is currently a direct implementation, but we can make it into a trait  if we want to provide option for other failure detector algorithm/heuristic.

```rust
trait FailureDetector {
  fn report_heartbeat(node_id: &str); // register node heartbeat
  fn update_node_liveliness(); // computes living/dead nodes
  fn live_nodes(); // access list of live nodes
  fn dead_nodes(); // access list of dead nodes
}
```
- Discuss what's the best `PHI_TRESHOLD` and document.
- Do we want to distinguish between node restarts ? I think right now we only care about a node being up/fine to work with.

The failure detector needs these adjustable options
 - window_size: usize, // heartbeat sampling window size
 - max_interval: Duration, // maximum heartbeat interval for heartbeat to be taken into account
 - initial_interval: Duration, // initial interval used when the was no previous sample value (at node startup)
 - PHI_TRESHOLD // phi threshold above which a node is considered down.
 
Currently, we can accepted a `config` struct that contains these options when constructing `ScuttleButt` instance. This has the advantage of not exposing the failure detector. But if choose to go with a trait we might have to expose PhiFailureDetector with it's option.

@guilload

**Comment by guilload** [comment]
Summary of our last chat on Discord:
- reuse Cassandra default values for now
- tracking node restarts is outside the scope of this PR
- design configuration objects and constructors that make testing easier
- switch to a `FailureDectector` trait only if necessary (mocking?)
- switch from `Mutex` to `RwLock` (nice to have)

TODOs:
- unit tests
- gossip with dead nodes
