### ISSUE TITLE
Prevent KV with a value longer than 500B.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/scuttlebutt#6]
Right now scuttlebutt relies on UDP with a hardcoded mtu of 1KB.

**Comment by evanxg852000** [comment]
Right now invariants like this are handled with `assert!` should we construct Error type and propagate or stick with `assert` for this case?

**Comment by fulmicoton** [comment]
Good question. usually `Error` is better for an API like this, but I think we can stick to assert in this very case.
